### ISSUE TITLE
Unexpected Buffersize on small Sensor

### ISSUE THREAD

**Issue by stdlogicvector** [JohnDMcMaster/gxs700#10]
I have a Size 1 (small) GXS-700) which returns an unexpected buffer size when trying to force-capture an image (haven't tried auto triggering). The returned size varies (e.g. 11426325, 11392746, 11426492, 11380779, ...).

Here is the dump info:
```
Waiting for device to come up


Found device (post-FW): Gendex GXS700SM (post enumeration)
Bus 002 Device 005: ID 5328:2020
Up after 1.9 sec
Init state: 1
S/N (flash): 1093330312
S/N (EEPROM): 1093330312
  S/N guess: blue Gendex (size 1)
Writing to dump/1093330312

Versions
MCU:     0.5.10
FPGA:    0.4.4
FGPA WG: 0.4.5

FPGA signature: 0x1234
State: 1
Error: 0
Trigger params: b'000301f4'
Int time: 700
Img ctr: b'5000000050000000'
Sensor dimensions: 1040w x 1552h

Dumping RAM
Dumping EEPROM
Dumping flash
Dumping register space
```
And here is the output from the capture:

```
Preparing capture
Init state: 1
Init state: 1
Forcing trigger
New state 2 (scan 0)
scan 0 (state 2)
New state 4 (scan 836)
Ready (state 4)
Traceback (most recent call last):
  File "/home/konstantin/Code/Python/xray/gxs700/main.py", line 78, in <module>
    main()
  File "/home/konstantin/Code/Python/xray/gxs700/main.py", line 55, in main
    raw_main.run(
  File "/home/konstantin/Code/Python/xray/gxs700/gxs700/raw_main.py", line 63, in run
    gxs.cap_binv(imgn, cb, force_trig=force_trig, xr=xr)
  File "/home/konstantin/Code/Python/xray/gxs700/gxs700/usbint.py", line 877, in cap_binv
    imgb = self._cap_bin(scan_cb=scan_cb, force_trig=force_trig, xr=xr)
  File "/home/konstantin/Code/Python/xray/gxs700/gxs700/usbint.py", line 856, in _cap_bin
    return self._cap_frame()
  File "/home/konstantin/Code/Python/xray/gxs700/gxs700/usbint.py", line 743, in _cap_frame
    ret = self._cap_frame_inter()
  File "/home/konstantin/Code/Python/xray/gxs700/gxs700/usbint.py", line 812, in _cap_frame_inter
    raise Exception("Unexpected buffer size. Want %d, got %d" %
Exception: Unexpected buffer size. Want 3228160, got 11436827

```

I also tried capturing an image under windows with original driver and VixWin. The testimage generator returns an image, but autoexposure crashes the program. Here is the log output:
```
[3/12/2021 21:39:36] *************************************: 0
[3/12/2021 21:39:36] GXS-700 Driver Initialization Success: 0
[3/12/2021 21:39:36] Number of GXS-700 Sensors Found: 1
[3/12/2021 21:39:36] Found Sensor-(SN): 1093330312
[3/12/2021 21:39:36] Number of GXS-700 Sensors Found: 1
[3/12/2021 21:39:37] Sensor Armed Successfully: 1093330312
[3/12/2021 21:39:37] Number of GXS-700 Sensors Armed: 1
[3/12/2021 21:39:37] GXS-700 Sensor Armed: 1093330312
[3/12/2021 21:39:48] Simulation Mode Turned On: 0
[3/12/2021 21:39:49] Number of GXS-700 Sensors Armed: 1
[3/12/2021 21:39:49] GXS-700 Sensor Armed: 1093330312
[3/12/2021 21:39:50] GXS-700 Sensor X-Ray Detected: 0
[3/12/2021 21:39:50] Watchdog Timer Started: 0
[3/12/2021 21:39:50] Image Ready Message Received From SN: 0
[3/12/2021 21:39:50] Sensor Armed Successfully: 0
[3/12/2021 21:39:50] Successfully Received 16-bit Image: 0
[3/12/2021 21:39:50] GXS-700 Sensor Image Transfer Done: 0
[3/12/2021 21:39:50] Watchdog Timer Stopped: 0
[3/12/2021 21:39:50] Sensor Disarmed: 0
[3/12/2021 21:39:50] Simulation Mode Turned Off: 0
[3/12/2021 21:39:50] Number of GXS-700 Sensors Found: 1
[3/12/2021 21:39:50] Found Sensor-(SN): 1093330312
[3/12/2021 21:39:51] Number of GXS-700 Sensors Found: 1
[3/12/2021 21:39:51] Sensor Armed Successfully: 1093330312
[3/12/2021 21:39:51] Number of GXS-700 Sensors Armed: 1
[3/12/2021 21:39:51] GXS-700 Sensor Armed: 0
[3/12/2021 21:39:51] GXS-700 Sensor Unarmed: 0
[3/12/2021 21:39:51] Number of GXS-700 Sensors Armed: 1
[3/12/2021 21:39:51] GXS-700 Sensor Armed: 0
[3/12/2021 21:42:58] GXS-700 Sensor X-Ray Detected: 1093330312
[3/12/2021 21:42:58] Watchdog Timer Started: 0
[3/12/2021 21:42:59] Image Ready Message Received From SN: 1093330312
[3/12/2021 21:42:59] Failed To Receive 16-bit Image: 30
[3/12/2021 21:43:9] Watchdog Timer Reset: 0
[3/12/2021 21:43:14] GXS-700 Driver Initialization: 0
[3/12/2021 21:43:14] GXS-700 Driver Initialization Success: 0
[3/12/2021 21:43:14] Premature X-Ray Detected.: 0
[3/12/2021 21:43:19] GXS-700 Sensor Unplugged: 0

```

Could this just be a problem with the data reception? Maybe something wrong with the USB-parameters? Or might the firmware be broken and flashing an intact image would fix it?

**Comment by stdlogicvector** [comment]
Addendum: I tried the test image capture modes with the python script and they all return the "unexpected buffer size" error with varying wrong sizes. The vbar test image worked under windows...so I suspect (hope, even) there might just be a problem with the code.

My firmware  SL: SL2080302-G1, ST: st3_fccmosd r12.3, 2/20/2010

Are there dumps available from known working Size 1 sensors?

**Comment by stdlogicvector** [comment]
I think I found the problem. There is a stray call to str() on the returned data in https://github.com/JohnDMcMaster/gxs700/blob/c61ea8bf7ef5694e7aa793414a6bd201a7214e39/gxs700/usbint.py#L810

I removed this and now I get an image that looks like the darkframes are supposed to look. Trying with x-rays next.

**Comment by JohnDMcMaster** [comment]
Oh nice! That sound about right...there was a python3 conversion and small size was probably not tested well. can you make a PR?

**Comment by JohnDMcMaster** [comment]
Think this is done? Please reopen if not. Thanks again for your PR!
