### ISSUE TITLE
BAD INSTALLATION

### ISSUE THREAD

**Issue by MarcoMI2020** [JohnDMcMaster/gxs700#9]

**Comment by MarcoMI2020** [comment]
dear John, 

i own a gendex sensor gxs700 acquired from the bay. During some googling i got into your great project. i tried to follow your installation procedure but i get the below error messages: 


Traceback (most recent call last):
  File "/usr/local/bin/gxs700-dump-dev", line 4, in <module>
    __import__('pkg_resources').run_script('gxs700==2.0.0', 'gxs700-dump-dev')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/gxs700-2.0.0-py3.8.egg/EGG-INFO/scripts/gxs700-dump-dev", line 24, in <module>
  File "/usr/local/lib/python3.8/dist-packages/gxs700-2.0.0-py3.8.egg/gxs700/usbint.py", line 269, in __init__
  File "/usr/local/lib/python3.8/dist-packages/gxs700-2.0.0-py3.8.egg/gxs700/usbint.py", line 181, in find_dev
  File "/usr/local/lib/python3.8/dist-packages/gxs700-2.0.0-py3.8.egg/gxs700/usbint.py", line 165, in open_dev
  File "/usr/local/lib/python3.8/dist-packages/gxs700-2.0.0-py3.8.egg/gxs700/usbint.py", line 211, in load_all
  File "/usr/local/lib/python3.8/dist-packages/usb1/__init__.py", line 2171, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/usr/local/lib/python3.8/dist-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/local/lib/python3.8/dist-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

i am using an Ubuntu 20.10 release with Python 3 distribution. I also tried to use the same version you had so 16.4 in order to follow exactly the same procedure... but the issue is always the same. I am not an expert in Python 3 programming .. so i don't know how to solve the problem. 

I tried to follow the same installation procedure also on a Raspberry PI3+. in this case it can recognize the sensor but.. i have always an error. 

May you help me? I would like to make it work on Ubuntu 20.10 

Thanks in advance for your time and your precious support,

BR
Marco

**Comment by JohnDMcMaster** [comment]
Oops, unfortunately I missed this ticket. Looks like you either need to "sudo" the command or install the udev rules. Please let me know if this ticket is still relevant.

**Comment by JohnDMcMaster** [comment]
Closing old ticket with no response. Please re-open if you are still having issues
